# Change this S3 Access to Your account
[development]
aws_access_key_id = 'ABCDEFGHIJKLMNOPQRS'
aws_secret_access_key = 'secret_secret_access'
[production]
aws_access_key_id = 'ABCDEFGHIJKLMNOPQRS'
aws_secret_access_key = 'secret_secret_access'
