[development]
aws_access_key_id = 'ABCDEFGHIJKLMNOPQRS'
aws_secret_access_key = 'fakeebNbeSi3V0vrW34bFbV0vrW34bE8ChMBA+p3+'
[production]
aws_access_key_id = 'ABCDEFGHIJKLMNOPQRS'
aws_secret_access_key = 'fakeebNbeSi3V0vrW34bFbV0vrW34bE8ChMBA'
